# Use > as recipe prefix instead of TAB
.RECIPEPREFIX = >

# Disable Guile auto-compilation to keep build output clean
export GUILE_AUTO_COMPILE = 0

M4 = m4
M4FLAGS = 
M4_LAYOUT = src/m4/layout.m4
M4_NEWS = src/m4/news.m4
M4_CONTENT = src/news-index.m4
M4_ALL = $(M4_LAYOUT) $(M4_NEWS) $(M4_CONTENT)

# Ensure directories exist
$(shell mkdir -p public public/articles scripts)

# Static pages - output to public/
public/%.html: src/%.m4 $(M4_ALL) src/templates/header.html.m4 src/templates/footer.html.m4
> $(M4) $(M4FLAGS) $(M4_ALL) $< > $@

# Articles - output to public/articles/
public/articles/%.html: src/articles/%.org $(M4_LAYOUT) src/m4/article.m4 src/templates/header.html.m4 src/templates/footer.html.m4 scripts/export-article-body.el scripts/wrap-article.scm scripts/update-news.scm scripts/detect-file-changes.scm
> @if [ -d src/articles/$* ]; then \
>  mkdir -p public/articles/$*; \
>  cp -r src/articles/$*/* public/articles/$*/; \
>  echo "Copied images for $*"; \
> fi
> @echo "Exporting $< to HTML body..."
> @emacs --batch --script scripts/export-article-body.el $< src/articles/$*.html
> @guile scripts/wrap-article.scm $< src/articles/$*.html $@
> @guile scripts/update-news.scm $< $@
> @$(MAKE) pages

# Artilecs index - generated by elisp + guile
public/articles/index.html: $(wildcard src/articles/*.org) $(M4_LAYOUT) src/articles-index.m4 src/templates/header.html.m4 src/templates/footer.html.m4 scripts/extract-articles-metadata.el scripts/update-article-index.scm scripts/detect-file-changes.scm
> @echo "Generating articles index..."
> @guile scripts/update-article-index.scm
> @echo "Generated $@"

# Build all articles
articles: $(patsubst src/articles/%.org,public/articles/%.html,$(wildcard src/articles/*.org)) public/articles/index.html

# Build static pages
pages: public/index.html public/old.html public/articles/index.html

# Build everything
all: pages articles

# Clean generated files
clean:
> rm -rf public/*.html public/articles/* src/articles/*.html

# Local preview server
serve:
> @echo "Starting local server at http://localhost:8000"
> @echo "Press Ctrl+C to stop"
> @guile scripts/serve.scm

.PHONY: all clean articles pages serve
